config/routes.rb
Rails.application.routes.draw do

  devise_for :users  
  resources :recipes

  root to: "recipes#index"
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
	has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base

	has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base

	has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	
	belongs_to :food_type
	belongs_to :food_preference
	belongs_to :cuisine

	DIFFICULTY=%w(Easy Medium Hard)

	validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
	helper_method :sidebar_values
	
	def sidebar_values
		@food_preferences = FoodPreference.all
		@food_types = FoodType.all
		@cuisines = Cuisine.all
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_header.html.erb
<div class="container">
	<ul class="nav navbar-nav pull-right">
		<% if user_signed_in? %>
			<li><%=link_to "#{current_user.email}" %></li>
			<li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		<%else%>
		  <li><%= link_to "Login", new_user_session_path %></li>
		  <li class="active"><%= link_to "SignUp", new_user_registration_path %></li>
		<% end %>
	</ul>
</div>	

<!-- Static navbar -->
<div class="navbar navbar-static-top">
	<div class="container">
		<button type="button" class="navbar-toggle"
		data-toggle="collapse" data-target=".nav-
		collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</button>

		<a class="navbar-brand" href="#"><%= link_to "CN", root_path %></a>
		<div class="nav-collapse collapse">
		
		<ul class="nav navbar-nav">
			<li class="active"><%= link_to "Recipes", recipes_path %></li>
		</ul>

		<ul class="nav navbar-nav pull-right">
			<% if user_signed_in? %>
					<li><%=link_to "#{current_user.email}" %></li>
					<li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				
				<%else%>

					<li><%= link_to "Login", new_user_session_path %></li>
					<li class="active"><%= link_to "SignUp", new_user_registration_path%></li>
			<%end%>
		</ul>
	</div><!--/.nav-collapse -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cn</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <div class="container">

    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
        <%= message %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-lg-2">
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Food Preferences</div>
      
        <% FoodPreference.all.each do |fp| %>
          <p><%= fp.name%></p>
        <%end%>
      </div>
      
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Food Type</div>
      
        <% FoodType.all.each do |ft| %>
          <p><%= ft.name%></p>
        <%end%>
      </div>

      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Cuisine</div>
      
        <% Cuisine.all.each do |c| %>
          <p><%= c.name%></p>
        <%end%>
        </div>
      </div>
      
      <div class="col-lg-9">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cooking_time %>
    <%= f.text_field :cooking_time, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty_level %>
    <%= f.select :difficulty_level, Recipe::DIFFICULTY,{} , :class => "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :food_type %>
    <%= f.select(:food_type_id,
    options_from_collection_for_select(FoodType.all, :id,
    :name), {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :food_preference %>
    <%= f.select(:food_preference_id,
    options_from_collection_for_select(FoodPreference.all,
    :id, :name), {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :cuisine %>
    <%= f.select(:cuisine_id,
    options_from_collection_for_select(Cuisine.all, :id,
    :name), {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :ingredients %>
    <%= f.text_area :ingredients, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :procedure %>
    <%= f.text_area :procedure, :class => "form-control" %>
  </div>
  
  <div class="actions form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Show', @recipe %> |
  <%= link_to 'Back', recipes_path %>
</p>

app/views/recipes/index.html.erb
<p>
  <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-primary" %>
</p>

<h1>Listing Recipes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Difficulty level</th>
      <th>Food type</th>
      <th>Food preference</th>
      <th>Cuisine</th>
      <th>Ingredients</th>
      <th>Procedure</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.title, recipe %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_preference.name %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>        
        <% if user_signed_in? %>
          <td>
            <%= link_to 'Edit', edit_recipe_path(recipe), :class=> "label label-warning"  %>
          </td>
          <td>
            <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "label label-danger" %>
          </td>
        <% end %>  
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back', recipes_path %>
</p>

app/views/recipes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type_id %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference_id %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>